- src/getClassName.js
Using `<div styleName="root">` where `.root` isn't defined results in this compilation error:
```
Error in ./src/App.js
Module build failed: Error: ~/Δ/src/App.js: Module cannot be resolved.
at Array.map (native)
```
This is confusing as it's not clear whether it's referring to a JS or CSS module.
> Improved error messages

- src/getClassName.js
When a styleName fails to resolve, the current error message gives no indication of which styleName could not be found, and instead outputs the unhelpful message 'CSS module cannot be resolved.'
This PR improves that message by including the styleName and clarifying the messaging.
> Improve the module resolution error message.

- demo/README.md
The ~~non-secure~~ SSH github url issues a security warning and requests the user to verify the server IP and key before proceeding with the clone. Using the https URL eliminates the warning.
> Update to https repo URL

- src/conditionalClassMerge.js
- src/replaceJsxExpressionContainer.js
- src/resolveStringLiteral.js
- test/fixtures/react-css-modules/merges the resolved styleName with the existing className values/expected.js
e.g. prevents a classname of undefined from being leaked into dom
> className no longer merges if it is falsely

- src/index.js
- test/fixtures/react-css-modules/merges the resolved styleName with the existing className values/expected.js
- test/fixtures/react-css-modules/uses getClassName to resolve non-literal styleName (with already existing className)/expected.js
- test/fixtures/react-css-modules/uses getClassName to resolve non-literal styleName/expected.js
When this plugin is used, output content is changed between compiles as it uses random number in output when import is used without assign to variable (`import "./style.css";`). This causes output file hash changes between builds having equal input and long-term asset caching for web is not working.
My guess the random is used to identify imports so I replaced random with style file name and it's location in source to prevent clashes when the same file is imported multiple times (not sure if such case exists though).
Let me know if this is ok, I'm gonna adjust code style to your needs and add tests.
I guess the `process.env.NODE_ENV === 'test'` conditional and it's contents can be removed as well as `styleImportName` won't change anymore between tests?
> Prevent output file content changes between compiles

- README.md
- package.json
- src/requireCssModule.js
- src/schemas/optionsSchema.json
- test/fixtures/react-css-modules/applies extra plugins/actual.js
- test/fixtures/react-css-modules/applies extra plugins/bar.scss
- test/fixtures/react-css-modules/applies extra plugins/expected.js
- test/fixtures/react-css-modules/applies extra plugins/options.json
- test/fixtures/react-css-modules/resolves less stylesheets/options.json
Added support for extra postcss plugins. They can be specified in `"filetypes"` section of config like this:
```json
"filetypes": {
".scss": {
"syntax": "postcss-scss",
"plugins": ["postcss-nested"]
}
}
> Support for extra postcss plugins

- src/requireCssModule.js
I have a use case where we use a non `.css` extension and want to run `post-cssnext` and some other postcss plugins, but we have no specific syntax module we want to use. This change will just return null if you don't supply a syntax and still use the plugins.
> Don't require the syntax config in filetypes

- package.json
- src/index.js
> Fix the ajv-keywords "keyword select requires $data option" warning.

- src/getClassName.js
The default was not being set for non-namespaced styles.  This caused a bug where errors were not thrown for runtime style names, since the options are not passed in if they are only the defaults.
This can be tested by creating a dynamic `styleName` on an element, and verifying that an error is thrown.  In the currently released version, no error is thrown.  In this branch, it will be, as expected.
> Set missing default handleMissingStyleName option

- README.md
- demo/package.json
Removes the requirement that `webpack-dev-server` be installed as a global dependency
> Adding start script to demo

- README.md
This took me an age to work out.
> Add RN custom extension note to readme

- src/replaceJsxExpressionContainer.js
To address #137 
Output before the change:
```javascript
_react.default.createElement("div", {
className: (0, _getClassName2.default)(..., _styleModuleImportMap)
}), _react.default.createElement("div", {
className: _getClassName(..., _styleModuleImportMap)
...
```
After change:
```javascript
_react.default.createElement("div", {
className: (0, _getClassName2.default)(..., _styleModuleImportMap)
}), _react.default.createElement("div", {
className: (0, _getClassName2.default)(..., _styleModuleImportMap)
...
```
Appears to work fine with both Babel 6 and 7.
> Fix multiple JSX expression replacement for Babel 7

- src/createObjectExpression.js
- src/getClassName.js
- src/replaceJsxExpressionContainer.js
- src/resolveStringLiteral.js
I updated all of the exceptions and console warnings to make it easier to debug mistakes. My experience is that it's really hard to use this software because if you make a mistake, it's hard to figure out where it is. This impacts you the most when porting a large codebase.
See: https://github.com/gajus/babel-plugin-react-css-modules/issues/171
> Made it easier to debug mistakes

- README.md
I added some notes on porting as well as a link to: http://www.jjinux.com/2018/04/javascript-porting-from-react-css.html
This may be helpful to some people. Don't feel bad if you reject it because it's not helpful enough.
> Added some notes on porting

- demo/package.json
- demo/webpack.config.js
- package.json
This PR updates the presets and plugins used in the build-helper run script to use equivalent v7-packages from the @babel namespace. Additionally the demo dependencies and Webpack config are updated to make the Demo work.
> fix: update build command and dependencies

- demo/package.json
- src/index.js
- test/fixtures/react-css-modules/does not throw error on excluded JSXElement/input.js
- test/fixtures/react-css-modules/does not throw error on excluded JSXElement/options.json
- test/fixtures/react-css-modules/does not throw error on excluded JSXElement/output.js
Up for discussion.
> I pushed #215 for discussion if the approach of applying the exclude setting not only to the imported style files but also to the location of the JSXElements that request them is okay for the scope of this project.
Fixes #209
> WIP feat: respect exclude setting in JSXElement transform

- src/getClassName.js
Should fix #128
In `getClassName`, falsey values will return an empty string.
Empty string is returned instead of its own value, because in cases such as `<div className="a" styleName={null} />`, the resulting className should not be `"a null"`.
> fix: cannot read property 'split' of undefined

- src/getClassName.js
This PR is merely a better engineering. Similar to in the other files, `defaultOptions` is imported instead of separately defining default `handleMissingStyleName` option.
> refactor: using default handleMissingStyleName from schema

- package.json
Should fix #232
I'm sorry for the bug.
In `build-helper` script is now added schema which includes `optionsDefaults`.
> fix: unresolved optionsDefaults in babel helper

- src/getClassName.js
- src/index.js
There can be a potential bug with the options. For example if `autoResolveMultipleImports` is `false` and assuming the default is `true`,
```js
stats.opts.autoResolveMultipleImports || optionsDefaults.autoResolveMultipleImports
```
the result should not be `true`.
> fix: potential problem with default options

- README.md
The links to webpack's documents on hot module reloading was out of date
> Update hotmodule reloading webpack links

- src/createSpreadMapper.js
- test/fixtures/react-css-modules/handle spread attributes/input.js
- test/fixtures/react-css-modules/handle spread attributes/output.js
Should fix #244 
Sorry for the bug. When traversing the spread attributes, an element traverses spread attributes in children elements as well. This fix simply changes the traversal into a simple loop. I also add a test case for this one.
> fix: spread should not traverse children elements

- src/createSpreadMapper.js
- test/fixtures/react-css-modules/does not throw error if attribute has no name property/output.js
- test/fixtures/react-css-modules/handle spread attributes/output.js
The following is valid React:
```javascript
const props = null;
<div {...props} styleName='a' />;
```
On master, after https://github.com/gajus/babel-plugin-react-css-modules/pull/243, this compiles to:
```javascript
const props = null;
<div {...props} className={"foo__a" + (" " + (props.className || ""))} />;
```
However, this fails because it is trying to read the `className` property of `null`.
This PR fixes this (and updates the tests) by also compiling in a falsy-check around `props`:
```javascript
const props = null;
<div {...props} className={"foo__a" + (" " + (props ? props.className || "" : ""))} />;
```
> fix: Don't break when spreading falsy value

- README.md
I was setting up `babel-plugin-react-css-modules` (with [React Storybook](https://storybook.js.org/docs/guides/guide-react/)) and ran into a number of errors. And because I wasn't quite sure how this plugin worked, I wasn't quite sure how to fix the errors. Three days later the docs make way more sense did they did.
I've proposed a number of doc tweaks as well as a couple of new FAQ issues around the errors I was running into w/ proposed solutions. The solutions also give more insight into how the plugin works so that other folks using the plugin can inform themselves to hopefully solve their problems as well.
- I wanted to reformat the Options table because it's a nightmare to read because of the horizontal scrolling, but I left that out
- I saw a lot of StackOverflow questions with …
> chore(docs): Add error FAQs to docs
